### ISSUE TITLE
Scanner måste kolla om variablenamnet är tillåtet 

### ISSUE THREAD

**Issue by alexmitic** [JoCAlOs/izi-language#1]
Så att användaren inte använder bryt, loop osv som variabel namn. Scanner ska casta ILLEGAL_VARIABLE_IDENTIFIER error som kommer finnas i error klassen

**Comment by Nehliin** [comment]
I think this is better handled by the parser but I could add it to the scanner if it's not possible for a solution in the parser.

**Comment by cjerik** [comment]
I am in agreement that it should be handled by the parser. I think it's more reasonable for the parser to handle such errors since the scanner does not take context into consideration.

**Comment by alexmitic** [comment]
My only concern was that the parser would get to cluttered by all the possible errors so handling as many as possible in the Scanner would prevent that. But if you think handling it in the parser is better then we can close the issue as you guys are more insatta in those classes.

**Comment by cjerik** [comment]
Even though it might make the parser more cluttered I don't think it's suitable for the scanner to make such decisions

**Comment by Nehliin** [comment]
Parser it is.
