### ISSUE TITLE
Need more Error enums

### ISSUE THREAD

**Issue by Nehliin** [JoCAlOs/izi-language#6]
FAILED_TO_FIND_FILE (there is no file with that name in the correct directory)
ILLEGAL_FILE_TYPE  (the imported file type isn't supported)
FAILED_TO_READ_FROM_FILE

**Comment by alexmitic** [comment]
Should FAILED_TO_READ_FROM_FILE be a syntaxerror or runtimerror?

**Comment by Nehliin** [comment]
runtime errors

**Comment by alexmitic** [comment]
Fixat
