### ISSUE TITLE
Individual tokens for operators such as '+=' ?

### ISSUE THREAD

**Issue by Nehliin** [JoCAlOs/izi-language#7]
Do we want unique and individual tokens for the operators +=, -=, *=, ^= ?

They are treated as 2 separate tokens as of now

**Comment by cjerik** [comment]
I think it would be necessary for it to be that way. In the parser it would be quite weird to handle it as two separate tokens. Does anyone have any objection to that?

**Comment by Halliom** [comment]
No objections. We need to treat it as a separate operator in the parser.

**Comment by cjerik** [comment]
Superb! We add the tokens for the operators, and close the issue.
